# The URL the site will be built for
base_url = "https://rami3l.github.io"

# The site title and description; used in feeds by default.
title = "rami3l.github.io"
description = "My scratchpad."

theme = "archie-zola"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [{ name = "tags" }]

default_language = "en"

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
# control dark mode: auto | dark | toggle
mode = "toggle"
favicon = "/icon/favicon.png"
copyright = "rami3l"

useCDN = true

[[extra.translations.en]]
show_more = ""
previous_page = "< Previous"
next_page = "Next >"
posted_on = "on "
posted_by = "by"
read_time = "minute read"
all_tags = "Tags"
menus = [
    { name = "Home", url = "/", weight = 2 },
    { name = "Posts", url = "/posts", weight = 2 },
    # { name = "About", url = "/about", weight = 3 },
    { name = "Tags", url = "/tags", weight = 4 },
]

# config social icon info in the footer
[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/rami3l"
